package com.laundromat.others

object AppConstants {
    const val SUCCESS_CODE = "200"
    const val ERROR_CODE = "0"
    const val ANOTHER_USER_LOGGED_IN = "402"
    const val MOBILE = "mobile_no"
    const val DASHBOARD_CATEGORY = "cat_dashboard"
    const val DASHBOARD_BRAND = "brand_dashboard"
    const val TYPE_CATEGORY = "category"
    const val TYPE_BRANDS = "brand"
    const val PRODUCTS_GRID = "products_grid"
    const val PRODUCTS_LINEAR = "products_linear"
    const val FILETR_FROM_DROP_DOWN = "fromDropDown"
    const val WISH_LIST = "from_wish_list"
    const val FILTER_SEEKBAR = "seekbar"
    const val TAG_TEXTVIEW = "textView"
    const val TAG_EDITTEXT = "edittext"
    const val TAG_BUTTON = "button_view"
    const val TAG_RADIO_BUTTON = "radio_button"
    const val RUPEE_SYMBOL = "$"
    const val ADDRESS_PICKER_CODE = 32
    const val STRIPE_TOKEN_CODE = 212
    const val STRIPE_TOKEN_ID = "token_id"
    const val EMPTY_ID = ""
    const val PRICE_LOW = "price_low"
    const val PRICE_HIGH = "price_high"
    const val CONDITION_OLD = "condition_old"
    const val CONDITION_NEW = "condition_new"
    const val MOST_VIEWED = "most_viewed"
    const val NORMAL_SIZE = 330
    const val NOTIFICATION = "notification"
    const val COMMON_APP_FONT = "fonts/crimson_text_regular.ttf"
    const val CREAMSON_BOLD = "fonts/CrimsonText-Bold.ttf"
    const val CREAMSON_SEMI_BOLD = "fonts/CrimsonText-SemiBold.ttf"
    const val LOTO_BOLD = "fonts/lato.bold.ttf"
    const val LOTO_HEAVY = "fonts/lato.heavy.ttf"
    const val CONSTANT_TIMING: Long = 500
    const val ACTIVTY_ENTER_ANIMATION = 0
    const val ACTIVTY_EXIT_ANIMATION = 0
    const val FROM_LOGIN = "from_login"
    const val FROM_DASHBOARD = "from_dashboard"
    const val FROM_REGISTRATION = "from_registration"
    const val INTENT_FROM = "activity_from"
    const val API_STATUS_KEY = "error"
    const val REQUIRED_SUCCESS_CODE = "200"
    const val MSG = "msg"
    const val TOKEN_EXPIRED_CODE = "404"
    const val SUCCESS = "success"
    const val AN_ERROR = "Server Issue.Pls try again later"
    const val LONG_TIME: Long = 2000
    const val APP_NAME = "Loyalty"
    var APP_FIRST_TIME_DILOGE = "NO"
}